config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable,
         :omniauthable, omniauth_providers:[:twitter]
         
  validates :name, presence: true
         
  def self.find_or_create_from_oauth(auth)
    find_or_create_by(provider: auth["provider"], uid: auth["uid"]) do |user|
      user.provider = auth["provider"]
      user.uid      = auth["uid"]
      user.name     = auth["info"]["nickname"]
      user.email    = User.dummy_email(auth)
      user.password = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end
  end
  
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
      end
    else
      super
    end
  end
  
  private
    def self.dummy_email(auth)
      "#{auth.uid}-#{auth.provider}@example.com"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
    protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  # (省略)...

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    callback_from :twitter
  end
  
  def failure
    redirect_to root_url
  end

  private

    def callback_from(provider)
      provider = provider.to_s
  
      @user = User.find_or_create_from_oauth(request.env['omniauth.auth'])
  
      if @user.persisted?
        flash[:notice] = I18n.t('devise.omniauth_callbacks.success',
                                  kind: provider.capitalize)
        session[:user_id] = @user.id
        sign_in_and_redirect @user, event: :authentication
      else
        session["devise.#{provider}_data"] = request.env['omniauth.auth']
        redirect_to new_user_registration_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # ページ事の完全なタイトルを返します
  def full_title(page_title = '')
    base_title = "名刺管理サービス"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by <a href="https://twitter.com/1000ba_Penguin"
      target="_blank" rel="noopener noreferrer">千羽ペンギン</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <%= link_to "カードホルダー", root_path, id: "logo" %>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <LI><%= link_to current_user.name, root_path %></LI>
            <LI><%= link_to 'プロフィール変更', edit_user_registration_path %></LI>
            <LI><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></LI>
          <% else %>
            <li><%= link_to "ホーム",   root_path %></li>
            <li><%= link_to 'サインアップ', new_user_registration_path %></li>
            <li><%= link_to 'ログイン', new_user_session_path %></li>
          <% end %>
          <li><%= link_to "ヘルプ",   help_path %></li>
        </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "ヘルプ") %>
<div class="center jumbotron">
  <h1>ヘルプページ</h1>
  <h2>
    不具合等ありましたら、下記から連絡をお願いします。
    <li>
      Twitter: <a href="https://twitter.com/1000ba_Penguin"
        target="_blank" rel="noopener noreferrer">千羽ペンギン</a>
    </li>
    <li>
      Blog <a href="https://obenkyo-log.com/"
        target="_blank" rel="noopener noreferrer">開発日記</a>
    </li>
  </h2>
</div>
  

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>
    Welcome to the<br>
    BUSINESS CARD HOLDER
  </h1>
  
  <h2>
    名刺の管理・登録を行います。<br>
    また、自分の名刺を他のユーザーに簡単に共有できます。
  </h2>
  
  <%= link_to "サインアップ!", '#', class: "btn btn-lg btn-primary" %>
</div>